### ISSUE TITLE
Error while executing CRON The requested Payment Method is not available

### ISSUE THREAD

**Issue by seansan** [ho-nl/Ho_Customer#6]
Dont know if this is a real error. But found in logs ... 

```
Cron error while executing ho_customer_create_customers_from_orders:

exception 'Mage_Core_Exception' with message 'The requested Payment Method is not available.' in /home/user/domains/domain.com/public_html/app/Mage.php:616
Stack trace:
#0 /home/user/domains/domain.com/public_html/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('The requested P...')
#1 /home/user/domains/domain.com/public_html/app/code/core/Mage/Payment/Model/Observer.php(46): Mage_Payment_Model_Info->getMethodInstance()
#2 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1338): Mage_Payment_Model_Observer->salesOrderBeforeSave(Object(Varien_Event_Observer))
#3 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Payment_Model_Observer), 'salesOrderBefor...', Object(Varien_Event_Observer))
#4 /home/user/domains/domain.com/public_html/app/Mage.php(468): Mage_Core_Model_App->dispatchEvent('sales_order_sav...', Array)
#5 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('sales_order_sav...', Array)
#6 /home/user/domains/domain.com/public_html/app/code/core/Mage/Sales/Model/Order.php(2049): Mage_Core_Model_Abstract->_beforeSave()
#7 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Sales_Model_Order->_beforeSave()
#8 /home/user/domains/domain.com/public_html/.modman/Ho_Customer/app/code/local/Ho/Customer/Model/GuestOrders.php(102): Mage_Core_Model_Abstract->save()
#9 /home/user/domains/domain.com/public_html/.modman/Ho_Customer/app/code/local/Ho/Customer/Model/GuestOrders.php(24): Ho_Customer_Model_GuestOrders->_createCustomer(Object(Mage_Sales_Model_Order))
#10 [internal function]: Ho_Customer_Model_GuestOrders->registerCustomers(Object(Aoe_Scheduler_Model_Schedule))
#11 /home/user/domains/domain.com/public_html/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(163): call_user_func_array(Array, Array)
#12 /home/user/domains/domain.com/public_html/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Schedule.php(541): Aoe_Scheduler_Model_Schedule->runNow(true)
#13 /home/user/domains/domain.com/public_html/.modman/Aoe_Scheduler/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#14 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1338): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#15 /home/user/domains/domain.com/public_html/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#16 /home/user/domains/domain.com/public_html/app/Mage.php(468): Mage_Core_Model_App->dispatchEvent('default', Array)
#17 /home/user/domains/domain.com/public_html/cron.php(76): Mage::dispatchEvent('default')
#18 {main}
```

**Comment by paales** [comment]
@seansan This is not a bug in Ho_Customer, but with old payment method, please consult your own developer to solve the issue.

**Comment by seansan** [comment]
OK

Maybe it can then skip this record?
